//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cliente.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string accept {
            get {
                return ResourceManager.GetString("accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Friend.
        /// </summary>
        public static string addFriend {
            get {
                return ResourceManager.GetString("addFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account is already logged.
        /// </summary>
        public static string alreadyLogged {
            get {
                return ResourceManager.GetString("alreadyLogged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email is invalid.
        /// </summary>
        public static string badEmail {
            get {
                return ResourceManager.GetString("badEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords are invalid.
        /// </summary>
        public static string badPassword {
            get {
                return ResourceManager.GetString("badPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        public static string black {
            get {
                return ResourceManager.GetString("black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel:.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code:.
        /// </summary>
        public static string code {
            get {
                return ResourceManager.GetString("code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Validation.
        /// </summary>
        public static string codeFail {
            get {
                return ResourceManager.GetString("codeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Code.
        /// </summary>
        public static string codeIncorrect {
            get {
                return ResourceManager.GetString("codeIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct Validation.
        /// </summary>
        public static string codeSuccess {
            get {
                return ResourceManager.GetString("codeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password:.
        /// </summary>
        public static string confirmPass {
            get {
                return ResourceManager.GetString("confirmPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deny.
        /// </summary>
        public static string deny {
            get {
                return ResourceManager.GetString("deny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have account?.
        /// </summary>
        public static string dontHaveAccount {
            get {
                return ResourceManager.GetString("dontHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elo:.
        /// </summary>
        public static string elo {
            get {
                return ResourceManager.GetString("elo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Elo:.
        /// </summary>
        public static string eloMax {
            get {
                return ResourceManager.GetString("eloMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email is already register.
        /// </summary>
        public static string emailRegistered {
            get {
                return ResourceManager.GetString("emailRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty fields.
        /// </summary>
        public static string emptyFields {
            get {
                return ResourceManager.GetString("emptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter an username.
        /// </summary>
        public static string enterUsername {
            get {
                return ResourceManager.GetString("enterUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in validation.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while logging in.
        /// </summary>
        public static string errorLogin {
            get {
                return ResourceManager.GetString("errorLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an error occurred.
        /// </summary>
        public static string errorOcurred {
            get {
                return ResourceManager.GetString("errorOcurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string es {
            get {
                return ResourceManager.GetString("es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends Request.
        /// </summary>
        public static string friendRequest {
            get {
                return ResourceManager.GetString("friendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        public static string friends {
            get {
                return ResourceManager.GetString("friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give Up.
        /// </summary>
        public static string giveUP {
            get {
                return ResourceManager.GetString("giveUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect credentials.
        /// </summary>
        public static string incorrectCredentials {
            get {
                return ResourceManager.GetString("incorrectCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitations.
        /// </summary>
        public static string invitations {
            get {
                return ResourceManager.GetString("invitations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        public static string join {
            get {
                return ResourceManager.GetString("join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Game.
        /// </summary>
        public static string joinGame {
            get {
                return ResourceManager.GetString("joinGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string load {
            get {
                return ResourceManager.GetString("load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches Played:.
        /// </summary>
        public static string matchPlayed {
            get {
                return ResourceManager.GetString("matchPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must write a message.
        /// </summary>
        public static string mustWrite {
            get {
                return ResourceManager.GetString("mustWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Game.
        /// </summary>
        public static string newGame {
            get {
                return ResourceManager.GetString("newGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection with the server.
        /// </summary>
        public static string noConecction {
            get {
                return ResourceManager.GetString("noConecction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t left blank spaces in the fields.
        /// </summary>
        public static string noSpaces {
            get {
                return ResourceManager.GetString("noSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password must include.
        /// </summary>
        public static string passInclude {
            get {
                return ResourceManager.GetString("passInclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. At least one lower case latter.
        /// </summary>
        public static string passRule1 {
            get {
                return ResourceManager.GetString("passRule1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. At least one upper case latter.
        /// </summary>
        public static string passRule2 {
            get {
                return ResourceManager.GetString("passRule2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. At least special character.
        /// </summary>
        public static string passRule3 {
            get {
                return ResourceManager.GetString("passRule3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4. At least one number.
        /// </summary>
        public static string passRule4 {
            get {
                return ResourceManager.GetString("passRule4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5. At least 8 characters lenght.
        /// </summary>
        public static string passRule5 {
            get {
                return ResourceManager.GetString("passRule5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put the code.
        /// </summary>
        public static string putCode {
            get {
                return ResourceManager.GetString("putCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking.
        /// </summary>
        public static string ranking {
            get {
                return ResourceManager.GetString("ranking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language updated.
        /// </summary>
        public static string refreshedLang {
            get {
                return ResourceManager.GetString("refreshedLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request already sent.
        /// </summary>
        public static string requestAlready {
            get {
                return ResourceManager.GetString("requestAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot send request to your own user.
        /// </summary>
        public static string requestAuto {
            get {
                return ResourceManager.GetString("requestAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Error.
        /// </summary>
        public static string requestError {
            get {
                return ResourceManager.GetString("requestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already Friends.
        /// </summary>
        public static string requestFriendAlready {
            get {
                return ResourceManager.GetString("requestFriendAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request rejected.
        /// </summary>
        public static string requestRejected {
            get {
                return ResourceManager.GetString("requestRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password are not the same.
        /// </summary>
        public static string samePass {
            get {
                return ResourceManager.GetString("samePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an user in the list.
        /// </summary>
        public static string selectUser {
            get {
                return ResourceManager.GetString("selectUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stats.
        /// </summary>
        public static string stats {
            get {
                return ResourceManager.GetString("stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request sent.
        /// </summary>
        public static string successRequest {
            get {
                return ResourceManager.GetString("successRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to Surrender?.
        /// </summary>
        public static string surrender {
            get {
                return ResourceManager.GetString("surrender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn of:.
        /// </summary>
        public static string TurnOf {
            get {
                return ResourceManager.GetString("TurnOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string userNotFound {
            get {
                return ResourceManager.GetString("userNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user is already taken.
        /// </summary>
        public static string userTaken {
            get {
                return ResourceManager.GetString("userTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        public static string validate {
            get {
                return ResourceManager.GetString("validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        public static string white {
            get {
                return ResourceManager.GetString("white", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win %:.
        /// </summary>
        public static string win {
            get {
                return ResourceManager.GetString("win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You.
        /// </summary>
        public static string you {
            get {
                return ResourceManager.GetString("you", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Lose :c.
        /// </summary>
        public static string youLose {
            get {
                return ResourceManager.GetString("youLose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Code is:.
        /// </summary>
        public static string yourCode {
            get {
                return ResourceManager.GetString("yourCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Win!!.
        /// </summary>
        public static string youWin {
            get {
                return ResourceManager.GetString("youWin", resourceCulture);
            }
        }
    }
}
