//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cliente.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accept.
        /// </summary>
        public static string accept {
            get {
                return ResourceManager.GetString("accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Friend.
        /// </summary>
        public static string addFriend {
            get {
                return ResourceManager.GetString("addFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This account is already logged.
        /// </summary>
        public static string alreadyLogged {
            get {
                return ResourceManager.GetString("alreadyLogged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back.
        /// </summary>
        public static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Black.
        /// </summary>
        public static string black {
            get {
                return ResourceManager.GetString("black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel:.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close.
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Code:.
        /// </summary>
        public static string code {
            get {
                return ResourceManager.GetString("code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incorrect Validation.
        /// </summary>
        public static string codeFail {
            get {
                return ResourceManager.GetString("codeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incorrect Code.
        /// </summary>
        public static string codeIncorrect {
            get {
                return ResourceManager.GetString("codeIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correct Validation.
        /// </summary>
        public static string codeSuccess {
            get {
                return ResourceManager.GetString("codeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm.
        /// </summary>
        public static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm Password:.
        /// </summary>
        public static string confirmPass {
            get {
                return ResourceManager.GetString("confirmPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deny.
        /// </summary>
        public static string deny {
            get {
                return ResourceManager.GetString("deny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You don&apos;t have account?.
        /// </summary>
        public static string dontHaveAccount {
            get {
                return ResourceManager.GetString("dontHaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elo:.
        /// </summary>
        public static string elo {
            get {
                return ResourceManager.GetString("elo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Max Elo:.
        /// </summary>
        public static string eloMax {
            get {
                return ResourceManager.GetString("eloMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email:.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The email is already register.
        /// </summary>
        public static string emailRegistered {
            get {
                return ResourceManager.GetString("emailRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empty fields.
        /// </summary>
        public static string emptyFields {
            get {
                return ResourceManager.GetString("emptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        public static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please, enter an username.
        /// </summary>
        public static string enterUsername {
            get {
                return ResourceManager.GetString("enterUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error in validation.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error while logging in.
        /// </summary>
        public static string errorLogin {
            get {
                return ResourceManager.GetString("errorLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a an error occurred.
        /// </summary>
        public static string errorOcurred {
            get {
                return ResourceManager.GetString("errorOcurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish.
        /// </summary>
        public static string es {
            get {
                return ResourceManager.GetString("es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exit.
        /// </summary>
        public static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friends Request.
        /// </summary>
        public static string friendRequest {
            get {
                return ResourceManager.GetString("friendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friends.
        /// </summary>
        public static string friends {
            get {
                return ResourceManager.GetString("friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incorrect credentials.
        /// </summary>
        public static string incorrectCredentials {
            get {
                return ResourceManager.GetString("incorrectCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitations.
        /// </summary>
        public static string invitations {
            get {
                return ResourceManager.GetString("invitations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join.
        /// </summary>
        public static string join {
            get {
                return ResourceManager.GetString("join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join Game.
        /// </summary>
        public static string joinGame {
            get {
                return ResourceManager.GetString("joinGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Load.
        /// </summary>
        public static string load {
            get {
                return ResourceManager.GetString("load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logout.
        /// </summary>
        public static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Matches Played:.
        /// </summary>
        public static string matchPlayed {
            get {
                return ResourceManager.GetString("matchPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must write a message.
        /// </summary>
        public static string mustWrite {
            get {
                return ResourceManager.GetString("mustWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Game.
        /// </summary>
        public static string newGame {
            get {
                return ResourceManager.GetString("newGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No connection with the server.
        /// </summary>
        public static string noConecction {
            get {
                return ResourceManager.GetString("noConecction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The password must include.
        /// </summary>
        public static string passInclude {
            get {
                return ResourceManager.GetString("passInclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1. At least one lower case latter.
        /// </summary>
        public static string passRule1 {
            get {
                return ResourceManager.GetString("passRule1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 2. At least one upper case latter.
        /// </summary>
        public static string passRule2 {
            get {
                return ResourceManager.GetString("passRule2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 3. At least special character.
        /// </summary>
        public static string passRule3 {
            get {
                return ResourceManager.GetString("passRule3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 4. At least one number.
        /// </summary>
        public static string passRule4 {
            get {
                return ResourceManager.GetString("passRule4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 5. At least 8 characters lenght.
        /// </summary>
        public static string passRule5 {
            get {
                return ResourceManager.GetString("passRule5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password:.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Put the code.
        /// </summary>
        public static string putCode {
            get {
                return ResourceManager.GetString("putCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ranking.
        /// </summary>
        public static string ranking {
            get {
                return ResourceManager.GetString("ranking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language updated.
        /// </summary>
        public static string refreshedLang {
            get {
                return ResourceManager.GetString("refreshedLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register.
        /// </summary>
        public static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Request already sent.
        /// </summary>
        public static string requestAlready {
            get {
                return ResourceManager.GetString("requestAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You cannot send request to your own user.
        /// </summary>
        public static string requestAuto {
            get {
                return ResourceManager.GetString("requestAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send Error.
        /// </summary>
        public static string requestError {
            get {
                return ResourceManager.GetString("requestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Already Friends.
        /// </summary>
        public static string requestFriendAlready {
            get {
                return ResourceManager.GetString("requestFriendAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Request rejected.
        /// </summary>
        public static string requestRejected {
            get {
                return ResourceManager.GetString("requestRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The password are not the same.
        /// </summary>
        public static string samePass {
            get {
                return ResourceManager.GetString("samePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select an user in the list.
        /// </summary>
        public static string selectUser {
            get {
                return ResourceManager.GetString("selectUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stats.
        /// </summary>
        public static string stats {
            get {
                return ResourceManager.GetString("stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Request sent.
        /// </summary>
        public static string successRequest {
            get {
                return ResourceManager.GetString("successRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to Surrender?.
        /// </summary>
        public static string surrender {
            get {
                return ResourceManager.GetString("surrender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username:.
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User not found.
        /// </summary>
        public static string userNotFound {
            get {
                return ResourceManager.GetString("userNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The user is already taken.
        /// </summary>
        public static string userTaken {
            get {
                return ResourceManager.GetString("userTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validate.
        /// </summary>
        public static string validate {
            get {
                return ResourceManager.GetString("validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome.
        /// </summary>
        public static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a White.
        /// </summary>
        public static string white {
            get {
                return ResourceManager.GetString("white", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Win %:.
        /// </summary>
        public static string win {
            get {
                return ResourceManager.GetString("win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You.
        /// </summary>
        public static string you {
            get {
                return ResourceManager.GetString("you", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You Lose :c.
        /// </summary>
        public static string youLose {
            get {
                return ResourceManager.GetString("youLose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your Code is:.
        /// </summary>
        public static string yourCode {
            get {
                return ResourceManager.GetString("yourCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You Win!!.
        /// </summary>
        public static string youWin {
            get {
                return ResourceManager.GetString("youWin", resourceCulture);
            }
        }
    }
}
